# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    name: Test scraper
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest coverage
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        coverage run -m pytest --noapi

    - name: Generate coverage report
      run: |
        coverage report --omit=test_parser.py,test_scraper.py
